/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/mandates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mandates */
        get: operations["list_mandates_api_mandates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mandates/{name}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mandate Review */
        get: operations["get_mandate_review_api_mandates__name__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catch All */
        get: operations["catch_all__path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MandateList */
        MandateList: {
            /** Mandates */
            mandates: components["schemas"]["MandateSummary"][];
        };
        /** MandateSummary */
        MandateSummary: {
            /** Name */
            name: string;
        };
        /**
         * ReviewCell
         * @description One grid cell. `value` is `null` for the four text columns and for a number the
         *     Reading could not compute — never `0`, which would read as a real answer.
         */
        ReviewCell: {
            /** Text */
            text: string;
            /** Value */
            value?: number | null;
        };
        /** ReviewDocument */
        ReviewDocument: {
            /** Mandate */
            mandate: string;
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            grid: components["schemas"]["ReviewGrid"];
            header: components["schemas"]["ReviewHeader"];
        };
        /** ReviewGrid */
        ReviewGrid: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: components["schemas"]["ReviewRow"][];
            totals: components["schemas"]["ReviewTotals"];
        };
        /** ReviewHeader */
        ReviewHeader: {
            /** Written */
            written: string | null;
            /** Stale Banner */
            stale_banner: string | null;
            /** Prices */
            prices: string;
            /** Mismatches */
            mismatches: string[];
        };
        /**
         * ReviewNote
         * @description A loud note or a yield note, detached from the terminal's fixed-width column. `label`
         *     is that column's own word — the verdict, or `"YIELD"` — carried even though it repeats
         *     `cells[10]` for a loud note: `"YIELD"` names a *kind* of note with no cell of its own, so
         *     the field has to exist regardless, and giving the loud note a different shape to avoid one
         *     repeated word would cost a branch on both ends of the wire. The ticker is deliberately
         *     absent — the row it lives on already names it.
         */
        ReviewNote: {
            /** Label */
            label: string;
            /** Text */
            text: string;
        };
        /** ReviewRow */
        ReviewRow: {
            /** Ticker */
            ticker: string;
            /** Cells */
            cells: components["schemas"]["ReviewCell"][];
            /** Unpriced */
            unpriced: boolean;
            /** Notes */
            notes: components["schemas"]["ReviewNote"][];
        };
        /** ReviewTotals */
        ReviewTotals: {
            /** Market Value */
            market_value: number;
            /** Unpriced */
            unpriced: number;
            /** Lines */
            lines: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_mandates_api_mandates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MandateList"];
                };
            };
        };
    };
    get_mandate_review_api_mandates__name__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catch_all__path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
