"""Render a `RosterView` for a terminal. Pure — string in, string out.

Everything numeric here comes straight off the view, which computed it from the corpus.
Nothing in this file is generated by a model, so a printed split cannot be wrong in the
way a narrated one can.
"""
from __future__ import annotations

from datetime import date

from core.rank import parse_date

from brain.retrieve import LEANS, RosterView

_INDENT = "  "

# How long a view of each horizon stays meaningfully "current". A four-month-old swing
# call is stale; a four-month-old macro call is not. Without this, a view someone last
# stated 14 months ago prints identically to one from last week — observed live, where
# TraderMayne's most recent BTC statement was 2025-05-29 and still labelled current.
STALE_AFTER_DAYS = {"scalp": 14, "swing": 45, "position": 240, "macro": 540}
_DEFAULT_STALE_DAYS = 120


def _staleness(published_at: str | None, horizon: str | None, today: date | None) -> str:
    if today is None:
        return ""
    published = parse_date(published_at)
    if published is None:
        return "  [UNDATED]"
    age = (today - published).days
    limit = STALE_AFTER_DAYS.get(horizon or "", _DEFAULT_STALE_DAYS)
    return f"  [STALE — {age}d old, {horizon or 'no horizon'} view]" if age > limit else ""


def format_passages(hits, *, query: str | None = None) -> str:
    """Render raw retrieved passages — the answer shape for a *concept* question.

    `format_view` answers "where does the roster stand on X" and needs the structured
    leg. A methodology question ("what is a judas swing") has no asset and no split;
    the passages ARE the answer, and the corpus answers it in the speaker's own words.

    Two deliberate differences from the EVIDENCE block in `format_view`:

    - **No truncation.** `format_view` cuts passages to 280 chars because there they
      merely corroborate a split that already stands on its own. Here a clipped passage
      is a clipped answer, and a half-sentence cannot be quoted or trusted.
    - **The score gets a health warning.** Absolute cosine is NOT comparable across
      queries — it depends on how the query itself embeds. "displacement" tops out at
      0.70 with five on-topic hits while "order block" tops out at 0.80; the first is
      not worse. IMPROVEMENTS.md §8 read the absolute numbers as "retrieval doesn't
      discriminate" and stood unchallenged for months. The consumer of this output is
      a model that will anchor on a number unless told what it means.
    """
    lines: list[str] = []
    if query:
        lines += [f"Q: {query}", ""]

    if not hits:
        return "\n".join([*lines, "No passages retrieved.", "", "The index covers the whole corpus, so this means the corpus genuinely does", "not cover it — not that extraction is lagging. Answer from what is here or", "say it isn't covered; do not fill the gap from outside knowledge."])

    lines.append(f"{len(hits)} passage(s), ranked by cosine similarity.")
    lines.append(f"{_INDENT}Scores are not comparable across queries — only against "
                 f"other hits for THIS one.")
    lines.append("")

    for i, hit in enumerate(hits, 1):
        person = getattr(hit, "person", "?")
        when = getattr(hit, "published_at", None) or "undated"
        ref = getattr(hit, "transcript_ref", "?")
        score = getattr(hit, "score", 0.0)
        text = " ".join(str(getattr(hit, "text", "")).split())
        lines.append(f"[{i}] {person} · {when} · {score:.3f} · {ref}")
        lines.append(f"{_INDENT}{text}")
        lines.append("")

    return "\n".join(lines).rstrip()


def _feed_label(name: str, view: RosterView) -> str:
    """Annotate a multi-author feed with its members at every mention. Attribution is
    feed-level, so an unlabelled `Technical Roundup` reads as one independent opinion
    when it is two people speaking together."""
    members = view.multi_author.get(name)
    return f"{name} [1 feed, {len(members)} voices: {', '.join(members)}]" if members else name


def format_view(view: RosterView, *, synthesis=None, question: str | None = None,
                today: date | None = None) -> str:
    asset = view.asset or "the roster"
    lines: list[str] = []

    if question:
        lines += [f"Q: {question}", ""]

    if not view.folded:
        return "\n".join([*lines, f"No current stance on {asset} in the corpus.", "", "Either nobody on the roster has covered it, or those transcripts have not", "been through `brain-extract` yet."])

    split = view.split
    counts = " · ".join(f"{lean} {split.counts[lean]}" for lean in LEANS)
    lines += [
        f"{asset} — {split.total_people} feed(s) with a current view",
        "",
        f"SPLIT   {counts}",
    ]
    if sum(split.counts.values()) > split.total_people:
        # Not an error: someone can be bullish on `macro` and bearish on `position` at
        # the same time, and both are real views. Say so, or the arithmetic looks broken.
        lines.append(f"{_INDENT}(exceeds feed count — a feed holding different leans at "
                     f"different horizons is counted under each)")
    for lean in LEANS:
        if split.people[lean]:
            names = ", ".join(_feed_label(n, view) for n in split.people[lean])
            lines.append(f"{_INDENT}{lean:<10}{names}")

    if view.changed:
        lines += ["", "CHANGED"]
        for f in view.changed:
            since = f" since {f.restated_since}" if f.restated_since else ""
            lines.append(
                f"{_INDENT}{_feed_label(f.person_canonical, view)}: "
                f"{f.previous.lean} -> {f.current.lean} "
                f"(as of {f.current.source.published_at}{since})"
            )

    lines += ["", "VIEWS"]
    for f in view.folded:
        s = f.current
        meta = " · ".join(x for x in (s.lean, s.conviction, s.horizon) if x)
        restated = f" · restated {f.restated}x" if f.restated else " · restated 0x"
        lines.append(
            f"{_INDENT}{_feed_label(f.person_canonical, view)} · {s.asset} · {meta} · "
            f"{s.source.published_at or 'undated'}{restated}"
            f"{_staleness(s.source.published_at, s.horizon, today)}"
        )
        lines.append(f"{_INDENT*2}{s.rationale}")
        if s.watching:
            lines.append(f"{_INDENT*2}watching: {s.watching}")
        lines.append(f"{_INDENT*2}{s.source.url}")

    if view.evidence:
        lines += ["", "EVIDENCE"]
        for i, hit in enumerate(view.evidence, 1):
            person = getattr(hit, "person", "?")
            when = getattr(hit, "published_at", "") or "undated"
            text = " ".join(str(getattr(hit, "text", "")).split())
            lines.append(f"{_INDENT}[{i}] {person}, {when}")
            lines.append(f'{_INDENT*2}"{text[:280]}"')

    if synthesis is not None:
        lines += ["", "SYNTHESIS", f"{_INDENT}{synthesis.answer}"]
        for c in synthesis.citations:
            when = c.get("published_at") or ""
            lines.append(f'{_INDENT}— {c.get("person", "?")} {when}: "{c.get("quote", "")}"')

    return "\n".join(lines)
