"""A night's movement, as the text that lands in the vault and the inbox. Pure.

String in, string out, nothing generated by a model — the same contract ``brain.report`` states
for the same reason: a printed number cannot be wrong in the way a narrated one can. The one
narrated section arrives already written and is dropped in as a block.

Two rules shape the layout:

**Empty sections do not print.** An absent heading says "nothing happened here" more clearly
than a heading with nothing under it, and a digest of empty headings is one nobody opens twice.

**A caveat goes above the rows it applies to.** A warning under the departures reads as a
footnote about something else; the reader has already taken the rows as fact by then.

Plain text, deliberately. It renders identically in a terminal, in the vault, and in a mail
client, which means one renderer and nothing to drift.
"""

from __future__ import annotations

from core.rank import parse_date
from core.trigger import ARMED, FIRED, NO_TRIGGER, NO_ZONE_TAG, UNREADABLE
from review.render import roster_text, where_text

from digest import diff, holdings
from digest.fmt import num

# How close to the monthly xAI cap before spend is worth a reader's attention. Below this the
# line is noise: the number is known, it is in the nightly log, and it has not changed in a way
# anyone can act on. At 90% the remaining headroom is one or two nights and that is a decision.
SPEND_LOUD_AT = 0.90

# Trigger states in words a person reads at 06:30. These are internal enum values and
# ``no_zone_tag`` reached the inbox unchanged for weeks — it is the *most common* previous state
# in the arrivals section, so the one line that carries entry and stop levels was also the one
# leaking a variable name.
#
# A state missing from this map prints as its raw value rather than as nothing. Ugly is
# recoverable; silence would hide that the map went stale behind ``core.trigger``.
_TRIGGER_WORDS = {
    NO_ZONE_TAG: "price had not reached the zone",
    NO_TRIGGER: "no break yet",
    ARMED: "armed",
    FIRED: "fired",
    UNREADABLE: "too thin to read",
}


def _in_words(state: str | None) -> str:
    return _TRIGGER_WORDS.get(state, state) if state else "unknown"


def _view_age(row: dict, as_of: str | None) -> str:
    """How old the newest thesis behind a row is, as `` · newest Nd``. Empty when unknown.

    ``agreement`` is a bare count: three people who last spoke in March render exactly like
    three who spoke yesterday. On 2026-08-26 RKLB showed ``agreement 3`` and all three views
    were months old. Printed unconditionally rather than past a threshold — a threshold is a
    decision that a row was not worth mentioning, and 40% of the voices behind that night's
    queue were stale by ``brain.report``'s own horizon-aware rule.

    Measured against the snapshot's own ``as_of``, never a clock. This module is pure, and a
    stale snapshot re-rendered tomorrow must not report different ages than it did today.
    """
    newest, taken = parse_date(row.get("newest_at")), parse_date(as_of)
    if newest is None or taken is None:
        return ""
    return f" · newest {(taken - newest).days}d"


def subject(delta: diff.QueueDelta, book=None, *, stale_as_of: str | None = None,
            problems: int = 0, repeat: bool = False, holdings_deltas=()) -> str:
    """The one line that has to work for someone who never opens the mail.

    Never empty. A blank or absent subject is indistinguishable from a job that did not run,
    which is the failure the always-send cadence exists to avoid — so a quiet night says
    "quiet" out loud.

    ``stale_as_of`` and ``problems`` are hoisted here because they are the two facts that change
    whether the rest of the line can be believed, and this is the only part many mornings get
    read at all.
    """
    if stale_as_of:
        return f"STALE — no snapshot recorded today; below describes {stale_as_of}"

    if delta.bootstrap:
        parts = [f"first run · {delta.qualified} qualified · nothing to diff yet"]
    else:
        parts = []
        if delta.arrived:
            parts.append(f"{len(delta.arrived)} at trigger")
        if delta.entered:
            parts.append(f"{len(delta.entered)} new")
        if delta.departed:
            parts.append(f"{len(delta.departed)} out")
        if delta.rolled:
            parts.append(f"{len(delta.rolled)} rezoned")
        parts.extend(_book_subject(book))
        parts.extend(holdings_subject(holdings_deltas))
        if not parts:
            parts.append(f"quiet · {delta.qualified} qualified")

    # Two digests went out on 2026-08-25 with byte-identical subjects and nothing in either
    # said it was the second. Marked rather than suppressed: a digest that silently does not
    # arrive is indistinguishable from a nightly that did not run, which is the failure the
    # always-send cadence exists to avoid.
    if repeat:
        parts.insert(0, "again")

    # Appended to every shape, including bootstrap. A first run that half-failed is still a
    # half-failed run, and the subject is where that has to show. ``!!`` stays leftmost — it is
    # the louder of the two markers and the eye lands there first.
    if problems:
        return f"!! {' · '.join(parts)} · {problems} problem(s)"
    return " · ".join(parts)


def markdown(delta: diff.QueueDelta, *, run=None, book=None, roster: str | None = None,
             roster_withheld: str | None = None, xai_month: float | None = None,
             xai_cap: float | None = None, xai_changed: bool = True,
             holding=(), resting: int = 0, holdings_deltas=(),
             stale_as_of: str | None = None, problems=()) -> str:
    """The digest body.

    ``roster`` is the one narrated section, passed in already written so this module keeps its
    no-model-output guarantee. ``roster_withheld`` is separate rather than folded into it,
    because an abstention printed under a heading reading "ROSTER MOVED" asserts the opposite
    of what it says — one ``str | None`` gave the caller no way to distinguish them.

    ``problems`` are the warnings collected while building. They print in the body because
    stderr goes to a rotated log the design assumes nobody opens, which made every warning in
    this package inert in production.
    """
    out: list[str] = []

    # First, above everything, because it decides whether any of the rest can be believed.
    if stale_as_of:
        out.append(f"STALE — no queue snapshot was recorded today. Everything below describes "
                   f"{stale_as_of}, not this morning. `setups` did not run, or could not write "
                   f"its snapshot.")
        out.append("")

    if delta.bootstrap:
        out.append(f"First run — {delta.qualified} candidates qualified. "
                   f"Nothing to compare against yet; tomorrow's digest has a diff.")
    else:
        out.extend(_caveats(delta))
        out.extend(_trigger_section(delta))
        out.extend(_entered_section(delta))
        # Above the departures: a rolled zone is the reason an asset can look like it left, and
        # a caveat under the rows it explains arrives after the reader has taken them as fact.
        out.extend(_rolled_section(delta))
        out.extend(_departed_section(delta))
        if delta.is_quiet:
            out.append(f"Quiet night — {delta.qualified} qualified, "
                       f"nothing entered, left, or reached its zone.")

    if roster_withheld:
        out.append("")
        out.append("ROSTER — WITHHELD")
        out.append(roster_withheld)
    elif roster:
        out.append("")
        out.append("ROSTER MOVED")
        out.append(roster)

    # Above the book's events: what you are in outranks what the account did overnight, and on
    # most nights the events are about orders that never became a position.
    out.extend(_holding_section(holding, resting))
    out.extend(_book_section(book))
    # Below the trading book on purpose. Everything above is time-sensitive — a zone reached
    # this morning, a fill overnight. A long-horizon account moves on a scale where one day
    # rarely matters, so it reads after the things that do.
    out.extend(_holdings_section(holdings_deltas))
    out.extend(_run_section(run, xai_month=xai_month, xai_cap=xai_cap,
                            xai_changed=xai_changed))
    out.extend(_problems_section(problems))
    out.extend(_provenance(delta))
    return "\n".join(out).strip() + "\n"


# ── sections ──────────────────────────────────────────────────────────────────

def _trigger_section(delta: diff.QueueDelta) -> list[str]:
    """Price arriving at a zone is the most time-sensitive thing the pipeline knows, so it goes
    first and carries the levels — a reader deciding at 06:30 should not have to open a terminal
    to see where the entry is."""
    if not delta.arrived:
        return []
    out = ["AT THE TRIGGER"]
    # Armed and fired before merely tagged: both are real, one is actionable today.
    for move in sorted(delta.arrived, key=lambda m: (m.kind != diff.TRIGGERED, m.asset)):
        row = move.row
        what = "armed" if move.kind == diff.TRIGGERED else "price reached the zone"
        origin = "new tonight" if move.new_tonight else _in_words(move.was)
        out.append(f"  {row['asset']:<8} {row['direction'].upper():<6} "
                   f"{row.get('zone_timeframe', '?')} · entry {num(row.get('entry'))} · "
                   f"stop {num(row.get('stop'))} · target {num(row.get('target'))}")
        out.append(f"           {what} ({origin}) · R:R {row.get('reward_risk', 0):.2f} · "
                   f"agreement {row.get('agreement', 0)}{_view_age(row, delta.as_of)}")
    out.append("")
    return out


def _entered_section(delta: diff.QueueDelta) -> list[str]:
    if not delta.entered:
        return []
    out = ["NEW IN QUEUE"]
    for row in sorted(delta.entered, key=lambda r: -r.get("score", 0)):
        out.append(f"  {row['asset']:<8} {row['direction'].upper():<6} "
                   f"score {row.get('score', 0):.2f} · R:R {row.get('reward_risk', 0):.2f} · "
                   f"agreement {row.get('agreement', 0)}{_view_age(row, delta.as_of)}")
    out.append("")
    return out


def _caveats(delta: diff.QueueDelta) -> list[str]:
    """Whole-night warnings, printed above everything they qualify.

    **Not folded into the departures section**, which is where they started. A moved
    ``score_version`` changes the scale of every score in the digest whether or not anything
    departed, so gating the warning on there being departures hid it on exactly the nights a
    reader would compare a score against yesterday's and be quietly wrong.
    """
    out: list[str] = []
    for name, (was, now) in sorted(delta.filters_changed.items()):
        out.append(f"NOTE — {name} moved {was} → {now}; anything that fell out below may be "
                   f"the filter moving, not the setups")
    if delta.score_version_changed:
        was, now = delta.score_version_changed
        out.append(f"NOTE — score_version moved {was} → {now}; scores are on a different scale "
                   f"than last night and are not comparable to it")
    if out:
        out.append("")
    return out


def _rolled_section(delta: diff.QueueDelta) -> list[str]:
    """One setup drawn against a different block. Its own section on purpose.

    Printed as an arrival plus a departure this was the same asset, same direction, in NEW IN
    QUEUE and FELL OUT of one email — which reads as the pipeline contradicting itself. Both
    entries are shown because the whole point is that the levels moved.
    """
    if not delta.rolled:
        return []
    out = ["ZONE MOVED — same thesis, different block"]
    for roll in sorted(delta.rolled, key=lambda r: r.asset):
        # Entry and R:R only. The stop moved too, but it is derived from the block and adds a
        # fourth and fifth number to a line whose job is "this got better or worse" — and under
        # $1 ``num`` renders it to six significant figures, which is noise nobody acts on.
        # Whether the trade improved is exactly what R:R says.
        out.append(f"  {roll.asset:<8} {roll.direction.upper():<6} "
                   f"entry {num(roll.was.get('entry'))} → {num(roll.now.get('entry'))} · "
                   f"R:R {roll.was.get('reward_risk', 0):.2f} → "
                   f"{roll.now.get('reward_risk', 0):.2f}")
    out.append("")
    return out


def _departed_section(delta: diff.QueueDelta) -> list[str]:
    if not delta.departed:
        return []
    out: list[str] = ["FELL OUT"]
    for gone in sorted(delta.departed, key=lambda d: d.row["asset"]):
        out.append(f"  {gone.row['asset']:<8} {gone.row['direction'].upper():<6} "
                   f"{gone.explanation}{_last_state(gone)}")
    out.append("")
    return out


def _last_state(gone: diff.Departure) -> str:
    """What the row last recorded, for a departure with no knowable cause.

    **Not a cause, and it must not be read as one.** Nothing here explains why the setup left;
    ``queue_snapshot`` records the qualified population and never a per-row reason, and the
    corpus-wide rejection counter cannot be attributed to a row. These are simply the numbers
    the row carried the last time it qualified, and they answer the question the bare line
    could not: whether losing this one mattered.

    Withheld where a real cause exists. "You marked it approved" is the point of that line, and
    padding it with score and R:R buries the one word worth reading.
    """
    if gone.reason != diff.UNKNOWN:
        return ""
    return (f" (was score {gone.row.get('score', 0):.2f} · "
            f"R:R {gone.row.get('reward_risk', 0):.2f})")


def _holding_section(holding, resting: int) -> list[str]:
    """What the account is in right now. The one standing state in a digest of diffs.

    It has to be standing, and that is the whole point: a position opened three weeks ago
    produces no event tonight, so every other section here is structurally incapable of
    mentioning it. The account held META and HOOD for three weeks and no digest had ever named
    either.

    Resting entries are counted, not listed. Five orders waiting at a price is worth knowing;
    listing them would double the section to say what ``uv run book`` says better.
    """
    if not holding:
        return []

    # Paper travels with the position for the reason it travels with a closed trade's number:
    # a fill that never had to find a buyer reads exactly like a real one.
    note = ", ".join(
        part for part in (
            f"{len(holding)} open",
            f"{resting} entries resting" if resting else "",
            "paper" if all(h.paper for h in holding) else "",
        ) if part)

    out = [f"HOLDING — {note}"]
    for held in holding:
        fill = (f"{held.qty:g} @ {num(held.fill_price)}"
                if held.qty is not None and held.fill_price is not None else "fill not recorded")
        since = f" · since {held.settled_at[:10]}" if held.settled_at else ""
        out.append(f"  {held.asset:<8} {(held.direction or '?').upper():<6} {fill} · "
                   f"stop {num(held.stop)} · target {num(held.target)}{since}")
    return ["", *out]


def _holdings_section(deltas) -> list[str]:
    """Verdict movement on the accounts you already hold — one block per portfolio.

    Prints when something moved **or** when an action is standing. The second condition is
    the interesting one: the diff correctly goes quiet on night two, but a TRIM you have not
    acted on is still a decision you owe. A count keeps it visible without a repeated
    paragraph, which is the thing that would teach the eye to skip this block entirely.

    A departure gets a mention, not a line with levels on it. It is asking nothing of you now;
    the fact worth carrying is only that it stopped asking.
    """
    out: list[str] = []
    for d in deltas:
        standing_loud = {v: n for v, n in d.standing.items() if v in holdings.LOUD and n}
        if not d.changed and not standing_loud and not d.unpriced:
            continue

        # PORTFOLIO, not HOLDINGS: `_holding_section` above already prints "HOLDING", and the
        # two sections are about different accounts entirely — one is the trading book, this is
        # the long-term money. A one-letter difference between two headings is not a difference.
        head = f"PORTFOLIO — {d.portfolio}"
        if d.bootstrap:
            # Eight arrivals on night one is not eight things that happened today, and without
            # this the first digest after wiring up an account reads as a violent Tuesday.
            head += " · first look, nothing to compare against yet"
        out += ["", head]

        for change in d.changed:
            verdict = change.reading.verdict
            was = "new to the file" if change.before is None else f"was {change.before}"
            if verdict in holdings.LOUD:
                out.append(f"  {verdict:<5} {change.ticker} — {was} · "
                           f"{roster_text(change.reading)} · {where_text(change.reading)}")
            else:
                out.append(f"  {'':<5} {change.ticker} — no longer {change.before}, "
                           f"now {verdict}")

        counts = " · ".join(f"{n} {v}" for v, n in sorted(standing_loud.items()))
        watching = d.standing.get("WATCH", 0)
        tail = [counts] if counts else []
        if watching:
            tail.append(f"{watching} WATCH")
        tail.append(f"{d.positions} positions")
        out.append(f"  {' · '.join(tail)} standing")

        if d.unpriced:
            # Above nothing and below everything, but present: a portfolio quietly short a few
            # rows reads as a portfolio, and `review`'s whole contract is that it never does.
            out.append(f"  no price for {', '.join(d.unpriced)} — "
                       f"run `fetch-prices --portfolio {d.portfolio}`")
    return out


def holdings_subject(deltas) -> list[str]:
    """The subject fragment. Counts positions that moved, never the standing total — a
    subject that said "5 TRIM" every morning for a week would stop being read on day two."""
    moved = sum(len(d.changed) for d in deltas)
    if not moved:
        return []
    return [f"{moved} holding{'' if moved == 1 else 's'} moved"]


def _book_section(book) -> list[str]:
    """Fills, kills, placements, refusals and closes since the previous nightly run.

    ``book`` is ``(events, notice)`` — the notice is a truncation warning, not an event, and is
    kept separate so it cannot be counted as one. Empty when nothing happened.
    """
    events, notice = _book_parts(book)
    if not events and not notice:
        return []
    out = ["", "BOOK"]
    out.extend(f"  {line}" for line in events)
    if notice:
        out.append(f"  {notice}")
    return out


def _book_parts(book) -> tuple[list, str | None]:
    """Accepts either ``(events, notice)`` or a bare list, so a caller with no notice can pass
    the events alone."""
    if not book:
        return [], None
    if isinstance(book, tuple):
        events, notice = book
        return list(events or []), notice
    return list(book), None


def _book_subject(book) -> list[str]:
    """Counts EVENTS only. The truncation notice used to live in the same list, so a capped
    night reported "13 book" for twelve events — wrong rather than absent, on the one line
    ``subject`` exists to make dependable."""
    events, _ = _book_parts(book)
    if not events:
        return []
    return [f"{len(events)} book"]


def _problems_section(problems) -> list[str]:
    """What broke while building this digest, in the message itself.

    These used to go only to stderr. In the nightly that is redirected into a rotated log the
    design explicitly assumes nobody opens, and the digest exits 0 on every degraded path — so
    every warning in this package was, as deployed, equivalent to ``pass``. A section that was
    dropped because something failed has to say so where the section would have been.
    """
    items = list(problems or [])
    if not items:
        return []
    return ["", "PROBLEMS — a section below may be missing or unexplained",
            *(f"  {p}" for p in items)]


def _provenance(delta: diff.QueueDelta) -> list[str]:
    """Which two snapshots this diff is between.

    Printed unconditionally and last. Without it a digest built from a stale snapshot — because
    ``setups`` failed, or could not write — renders as a real, internally consistent diff of the
    wrong night, and the vault note stamps today's date on it. Two run stamps make that visible
    without the reader having to know the failure exists.
    """
    return ["", f"     {delta.previous_run or '—'} → {delta.current_run or '—'}"]


def _run_section(run, *, xai_month: float | None, xai_cap: float | None,
                 xai_changed: bool = True) -> list[str]:
    """One line, unless something wants attention.

    Trends across runs are ``scripts/nightly_report.py``'s job and are deliberately not
    duplicated here — this answers only "did last night work".

    ``xai_changed`` is whether the month total moved since it was last printed; see
    ``state.xai_changed``. It gates only the spend line, never the step-health line above it.
    """
    if not run:
        return []
    steps = run.get("steps", []) or []
    bad = [s.get("name", "?") for s in steps if s.get("status") in ("fail", "warn")]
    # ``exit`` is the nightly's own ``WORST`` and is the authoritative field. Health was
    # recomputed from ``steps`` alone, and a step the nightly SKIPPED is absent from that list
    # rather than present-and-failed — so a truncated run and a clean one both read as "clean",
    # differing only in a step count the reader has no baseline for.
    code = run.get("exit", 0)
    # A step's status comes from its exit code, and several commands report a failure while
    # exiting 0 — `ingest-roster` aborting on a YouTube IP block is the case that prompted
    # this. The nightly catches those separately and records WHY here, because the step list
    # alone cannot say. Empty on rows written before the field existed, which is why the
    # can't-say wording below still has to exist.
    reasons = [r for r in (run.get("reasons") or []) if r]
    if bad:
        line = f"RUN  exit {code} · {len(bad)} step(s) not ok: {', '.join(bad)}"
    elif code and reasons:
        line = f"RUN  exit {code} · {len(steps)} steps"
    elif code:
        line = f"RUN  exit {code} · {len(steps)} steps, none individually flagged — see the log"
    else:
        line = f"RUN  clean · {len(steps)} steps"

    out = ["", line]
    out += [f"    {r}" for r in reasons]
    # Spend only speaks up near the cap. Below it the number is knowable, unchanged in any
    # actionable way, and already in the nightly log.
    #
    # And only when it MOVED. `ingest-x` is off by default, so the month total freezes and this
    # line otherwise fires on the identical number every night until the month rolls over. That
    # is an alarm nothing can clear, sitting directly under the step-health line — so it does
    # not just waste a row, it teaches the reader to skip the row that reports real failures.
    if (xai_changed and xai_month is not None and xai_cap
            and xai_month >= xai_cap * SPEND_LOUD_AT):
        # "Near" and "over" are different facts and the second is the one that wants acting on.
        # Reading "near the cap" beside a number visibly above it teaches the eye to skip both.
        where = "OVER the cap" if xai_month >= xai_cap else "near the cap"
        out.append(f"     xAI ${xai_month:.2f}/{xai_cap:.2f} this month — {where}")
    return out

