"""A night's movement, as the text that lands in the vault and the inbox. Pure.

String in, string out, nothing generated by a model — the same contract ``brain.report`` states
for the same reason: a printed number cannot be wrong in the way a narrated one can. The one
narrated section arrives already written and is dropped in as a block.

Two rules shape the layout:

**Empty sections do not print.** An absent heading says "nothing happened here" more clearly
than a heading with nothing under it, and a digest of empty headings is one nobody opens twice.

**A caveat goes above the rows it applies to.** A warning under the departures reads as a
footnote about something else; the reader has already taken the rows as fact by then.

Plain text, deliberately. It renders identically in a terminal, in the vault, and in a mail
client, which means one renderer and nothing to drift.
"""

from __future__ import annotations

from digest import diff
from digest.fmt import num

# How close to the monthly xAI cap before spend is worth a reader's attention. Below this the
# line is noise: the number is known, it is in the nightly log, and it has not changed in a way
# anyone can act on. At 90% the remaining headroom is one or two nights and that is a decision.
SPEND_LOUD_AT = 0.90


def subject(delta: diff.QueueDelta, book=None, *, stale_as_of: str | None = None,
            problems: int = 0) -> str:
    """The one line that has to work for someone who never opens the mail.

    Never empty. A blank or absent subject is indistinguishable from a job that did not run,
    which is the failure the always-send cadence exists to avoid — so a quiet night says
    "quiet" out loud.

    ``stale_as_of`` and ``problems`` are hoisted here because they are the two facts that change
    whether the rest of the line can be believed, and this is the only part many mornings get
    read at all.
    """
    if stale_as_of:
        return f"STALE — no snapshot recorded today; below describes {stale_as_of}"

    if delta.bootstrap:
        parts = [f"first run · {delta.qualified} qualified · nothing to diff yet"]
    else:
        parts = []
        if delta.arrived:
            parts.append(f"{len(delta.arrived)} at trigger")
        if delta.entered:
            parts.append(f"{len(delta.entered)} new")
        if delta.departed:
            parts.append(f"{len(delta.departed)} out")
        parts.extend(_book_subject(book))
        if not parts:
            parts.append(f"quiet · {delta.qualified} qualified")

    # Appended to every shape, including bootstrap. A first run that half-failed is still a
    # half-failed run, and the subject is where that has to show.
    if problems:
        return f"!! {' · '.join(parts)} · {problems} problem(s)"
    return " · ".join(parts)


def markdown(delta: diff.QueueDelta, *, run=None, book=None, roster: str | None = None,
             roster_withheld: str | None = None, xai_month: float | None = None,
             xai_cap: float | None = None, stale_as_of: str | None = None,
             problems=()) -> str:
    """The digest body.

    ``roster`` is the one narrated section, passed in already written so this module keeps its
    no-model-output guarantee. ``roster_withheld`` is separate rather than folded into it,
    because an abstention printed under a heading reading "ROSTER MOVED" asserts the opposite
    of what it says — one ``str | None`` gave the caller no way to distinguish them.

    ``problems`` are the warnings collected while building. They print in the body because
    stderr goes to a rotated log the design assumes nobody opens, which made every warning in
    this package inert in production.
    """
    out: list[str] = []

    # First, above everything, because it decides whether any of the rest can be believed.
    if stale_as_of:
        out.append(f"STALE — no queue snapshot was recorded today. Everything below describes "
                   f"{stale_as_of}, not this morning. `setups` did not run, or could not write "
                   f"its snapshot.")
        out.append("")

    if delta.bootstrap:
        out.append(f"First run — {delta.qualified} candidates qualified. "
                   f"Nothing to compare against yet; tomorrow's digest has a diff.")
    else:
        out.extend(_caveats(delta))
        out.extend(_trigger_section(delta))
        out.extend(_entered_section(delta))
        out.extend(_departed_section(delta))
        if delta.is_quiet:
            out.append(f"Quiet night — {delta.qualified} qualified, "
                       f"nothing entered, left, or reached its zone.")

    if roster_withheld:
        out.append("")
        out.append("ROSTER — WITHHELD")
        out.append(roster_withheld)
    elif roster:
        out.append("")
        out.append("ROSTER MOVED")
        out.append(roster)

    out.extend(_book_section(book))
    out.extend(_run_section(run, xai_month=xai_month, xai_cap=xai_cap))
    out.extend(_problems_section(problems))
    out.extend(_provenance(delta))
    return "\n".join(out).strip() + "\n"


# ── sections ──────────────────────────────────────────────────────────────────

def _trigger_section(delta: diff.QueueDelta) -> list[str]:
    """Price arriving at a zone is the most time-sensitive thing the pipeline knows, so it goes
    first and carries the levels — a reader deciding at 06:30 should not have to open a terminal
    to see where the entry is."""
    if not delta.arrived:
        return []
    out = ["AT THE TRIGGER"]
    # Armed and fired before merely tagged: both are real, one is actionable today.
    for move in sorted(delta.arrived, key=lambda m: (m.kind != diff.TRIGGERED, m.asset)):
        row = move.row
        what = "armed" if move.kind == diff.TRIGGERED else "price reached the zone"
        origin = "new tonight" if move.new_tonight else f"was {move.was}"
        out.append(f"  {row['asset']:<8} {row['direction'].upper():<6} "
                   f"{row.get('zone_timeframe', '?')} · entry {num(row.get('entry'))} · "
                   f"stop {num(row.get('stop'))} · target {num(row.get('target'))}")
        out.append(f"           {what} ({origin}) · R:R {row.get('reward_risk', 0):.2f} · "
                   f"agreement {row.get('agreement', 0)}")
    out.append("")
    return out


def _entered_section(delta: diff.QueueDelta) -> list[str]:
    if not delta.entered:
        return []
    out = ["NEW IN QUEUE"]
    for row in sorted(delta.entered, key=lambda r: -r.get("score", 0)):
        out.append(f"  {row['asset']:<8} {row['direction'].upper():<6} "
                   f"score {row.get('score', 0):.2f} · R:R {row.get('reward_risk', 0):.2f} · "
                   f"agreement {row.get('agreement', 0)}")
    out.append("")
    return out


def _caveats(delta: diff.QueueDelta) -> list[str]:
    """Whole-night warnings, printed above everything they qualify.

    **Not folded into the departures section**, which is where they started. A moved
    ``score_version`` changes the scale of every score in the digest whether or not anything
    departed, so gating the warning on there being departures hid it on exactly the nights a
    reader would compare a score against yesterday's and be quietly wrong.
    """
    out: list[str] = []
    for name, (was, now) in sorted(delta.filters_changed.items()):
        out.append(f"NOTE — {name} moved {was} → {now}; anything that fell out below may be "
                   f"the filter moving, not the setups")
    if delta.score_version_changed:
        was, now = delta.score_version_changed
        out.append(f"NOTE — score_version moved {was} → {now}; scores are on a different scale "
                   f"than last night and are not comparable to it")
    if out:
        out.append("")
    return out


def _departed_section(delta: diff.QueueDelta) -> list[str]:
    if not delta.departed:
        return []
    out: list[str] = ["FELL OUT"]
    for gone in sorted(delta.departed, key=lambda d: d.row["asset"]):
        out.append(f"  {gone.row['asset']:<8} {gone.row['direction'].upper():<6} "
                   f"{gone.explanation}")
    out.append("")
    return out


def _book_section(book) -> list[str]:
    """Fills, kills, placements, refusals and closes since the previous nightly run.

    ``book`` is ``(events, notice)`` — the notice is a truncation warning, not an event, and is
    kept separate so it cannot be counted as one. Empty when nothing happened.
    """
    events, notice = _book_parts(book)
    if not events and not notice:
        return []
    out = ["", "BOOK"]
    out.extend(f"  {line}" for line in events)
    if notice:
        out.append(f"  {notice}")
    return out


def _book_parts(book) -> tuple[list, str | None]:
    """Accepts either ``(events, notice)`` or a bare list, so a caller with no notice can pass
    the events alone."""
    if not book:
        return [], None
    if isinstance(book, tuple):
        events, notice = book
        return list(events or []), notice
    return list(book), None


def _book_subject(book) -> list[str]:
    """Counts EVENTS only. The truncation notice used to live in the same list, so a capped
    night reported "13 book" for twelve events — wrong rather than absent, on the one line
    ``subject`` exists to make dependable."""
    events, _ = _book_parts(book)
    if not events:
        return []
    return [f"{len(events)} book"]


def _problems_section(problems) -> list[str]:
    """What broke while building this digest, in the message itself.

    These used to go only to stderr. In the nightly that is redirected into a rotated log the
    design explicitly assumes nobody opens, and the digest exits 0 on every degraded path — so
    every warning in this package was, as deployed, equivalent to ``pass``. A section that was
    dropped because something failed has to say so where the section would have been.
    """
    items = list(problems or [])
    if not items:
        return []
    return ["", "PROBLEMS — a section below may be missing or unexplained",
            *(f"  {p}" for p in items)]


def _provenance(delta: diff.QueueDelta) -> list[str]:
    """Which two snapshots this diff is between.

    Printed unconditionally and last. Without it a digest built from a stale snapshot — because
    ``setups`` failed, or could not write — renders as a real, internally consistent diff of the
    wrong night, and the vault note stamps today's date on it. Two run stamps make that visible
    without the reader having to know the failure exists.
    """
    return ["", f"     {delta.previous_run or '—'} → {delta.current_run or '—'}"]


def _run_section(run, *, xai_month: float | None, xai_cap: float | None) -> list[str]:
    """One line, unless something wants attention.

    Trends across runs are ``scripts/nightly_report.py``'s job and are deliberately not
    duplicated here — this answers only "did last night work".
    """
    if not run:
        return []
    steps = run.get("steps", []) or []
    bad = [s.get("name", "?") for s in steps if s.get("status") in ("fail", "warn")]
    # ``exit`` is the nightly's own ``WORST`` and is the authoritative field. Health was
    # recomputed from ``steps`` alone, and a step the nightly SKIPPED is absent from that list
    # rather than present-and-failed — so a truncated run and a clean one both read as "clean",
    # differing only in a step count the reader has no baseline for.
    code = run.get("exit", 0)
    if bad:
        line = f"RUN  exit {code} · {len(bad)} step(s) not ok: {', '.join(bad)}"
    elif code:
        line = f"RUN  exit {code} · {len(steps)} steps, none individually flagged — see the log"
    else:
        line = f"RUN  clean · {len(steps)} steps"

    out = ["", line]
    # Spend only speaks up near the cap. Below it the number is knowable, unchanged in any
    # actionable way, and already in the nightly log.
    if xai_month is not None and xai_cap and xai_month >= xai_cap * SPEND_LOUD_AT:
        # "Near" and "over" are different facts and the second is the one that wants acting on.
        # Reading "near the cap" beside a number visibly above it teaches the eye to skip both.
        where = "OVER the cap" if xai_month >= xai_cap else "near the cap"
        out.append(f"     xAI ${xai_month:.2f}/{xai_cap:.2f} this month — {where}")
    return out

